from .Databases import DatabasesPageController, DatabasesServiceController
from .Dashboard import DashboardPageController, DashboardServiceController
from .Languages import LanguagesPageController, LanguagesServiceController
from .Network import NetworkServiceController, NetworkPageController
from .Tools import ToolsPageController, ToolsServiceController