from .Databases import DatabasesPageController, DatabasesServiceController
from .Dashboard import DashboardPageController, DashboardServiceController
from .Languages import LanguagesPageController, LanguagesServiceController
from .Network import NetworkPageController, NetworkServiceController
from .Tools import ToolsPageController, ToolsServiceController
from .Webserver import WebserverPageController, WebserverServiceController